create database customer_behavior;
use customer_behavior;
select * from customer_shopping_behavior;


--Q1 Whta Is The Total Revenue generated by male vs. female customer?

select gender, sum(purchase_amount_usd) as revenue
from customer_shopping_behavior
group by gender;

--Q2 Which Customer used a discount but still spent more then the average purchase amount
select customer_id, purchase_amount_usd
from customer_shopping_behavior
where discount_applied = 'yes' and purchase_amount_usd >=(select avg(purchase_amount_usd) from customer_shopping_behavior);

--Q3 Which Are The Top 5 products with the highest average review rating?
select top 5 item_purchased, avg(review_rating) as "average product rating"
from customer_shopping_behavior
group by item_purchased
order by avg(review_rating);

--Q4 Compare the average purchase amount between standard and express shipping?
select shipping_type,
round(avg (purchase_amount_usd),2)
from customer_shopping_behavior
where shipping_type in ('standard','express')
group by shipping_type;

--Q5 Do Subscribed customer spend more? compere average spend and total revenue between sucscribers and non-subscribers?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount_usd),2) as avg_spend,
round(sum(purchase_amount_usd),2) as total_revenue
from customer_shopping_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6 Which 5 Product have the highest percentage of purchase with discount applied?
select top 5 item_purchased,
round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc;

--Q7 Segment customer into new, returning, and loyel based on thair total number of previous purchase, and show the count of each segment?
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from customer_shopping_behavior
)

select customer_segment, count(*) as "number of customer"
from customer_type
group by customer_segment;

--Q8 What are the top 3 most purchased product withen each catagory?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,

ROW_NUMBER() over(partition by category order by count(customer_id)desc) as item_rank
from customer_shopping_behavior
group by category, item_purchased
)
select item_rank, category, item_purchased,total_orders
from item_counts
where item_rank <=3;


--Q9 Are Custome Who Repeat Buyers (more then 5 previous purchases ) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status;

--Q10 What Is The revenue contribution of each age group?
select age,
sum(purchase_amount_usd) as total_revenue
from customer_shopping_behavior
group by age
order by total_revenue desc; 